name: Install aqua
description: Install aqua https://aquaproj.github.io/ and install toos with aqua
inputs:
  aqua_version:
    description: installed aqua's version (e.g. v0.8.7)
    required: true
  install_path:
    description: aqua's install path
    required: false
  enable_aqua_install:
    required: false
    default: "true"
  aqua_opts:
    required: false
    default: "-l"
  working_directory:
    required: false
    default: ""
runs:
  using: composite
  steps:
    - run: |
        echo "::error ::aqua_version is required. https://github.com/aquaproj/aqua-installer"
        exit 1
      shell: bash
      if: inputs.aqua_version == ''

    - run: echo "${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin" >> $GITHUB_PATH
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      if: inputs.enable_aqua_install == 'true'
    - run: |
        echo "${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh
      if: runner.os == 'Windows' && inputs.enable_aqua_install == 'true'
      working-directory: ${{ inputs.working_directory }}

    - run: bash "${{github.action_path}}/action.sh"
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      env:
        AQUA_INSTALL_PATH: ${{ inputs.install_path }}
        AQUA_VERSION: ${{ inputs.aqua_version }}
        AQUA_OPTS: ${{ inputs.aqua_opts }}
