name: Install aqua
description: Install aqua https://aquaproj.github.io/ and install toos with aqua
inputs:
  aqua_version:
    description: installed aqua's version (e.g. v1.17.0)
    required: true
  install_path:
    description: aqua's install path
    required: false
  enable_aqua_install:
    required: false
    default: "true"
  aqua_opts:
    required: false
    default: "-l"
  working_directory:
    required: false
    default: ""
runs:
  using: node16
  main: dist/index.js
