#!/usr/bin/env bash
# aqua-installer - shell script to install aqua
# https://github.com/aquaproj/aqua-installer

set -eu
set -o pipefail || :

usage_exit() {
	echo "Usage: $0 [-v version]" 1>&2
	exit 1
}

uname_os() {
	local os
	os=$(uname -s | tr '[:upper:]' '[:lower:]')
	case "$os" in
		cygwin_nt*) os="windows" ;;
		mingw*) os="windows" ;;
		msys_nt*) os="windows" ;;
	esac
	echo "$os"
}

uname_arch() {
	local arch
	arch=$(uname -m)
	case $arch in
		x86_64) arch="amd64" ;;
		aarch64) arch="arm64" ;;
	esac
	echo "${arch}"
}

OS="$(uname_os)"
ARCH="$(uname_arch)"

install_path=${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin/aqua
if [ "$OS" = windows ]; then
	install_path=${AQUA_ROOT_DIR:-$HOME/AppData/Local/aquaproj-aqua}/bin/aqua.exe
fi

while getopts v: OPT
do
	case $OPT in
		v) AQUA_VERSION=$OPTARG
			;;
		\?) usage_exit
			;;
	esac
done

shift $((OPTIND - 1))

bootstrap_version=v2.30.0
checksums="891ce121345268e6b88006e0b2aee90dc6c14b1e42dad7b55f16f43799f49572  aqua_darwin_amd64.tar.gz
b8bc49d4ae48401a7f09c75a5f1dc9efbe360d3f54047a43d14ee15150e79061  aqua_darwin_arm64.tar.gz
933f4eff665f268b461e9897098c9ebbd10ca3b9277a901670e129226f434ec0  aqua_linux_amd64.tar.gz
18fc75c57300c42144c4262bb807277d0c5f32685a0e49489da31c46fc8e03e0  aqua_linux_arm64.tar.gz
7c9898a59405d404bd6f7fd736287d2cdfaac99d81106c8b7323124a652c13c4  aqua_windows_amd64.zip
5c09c6ed383e120bfad73a262498d9647defd6ce8f8c710310b18fa25ba9d221  aqua_windows_arm64.zip"

filename=aqua_${OS}_${ARCH}.tar.gz
if [ "$OS" = windows ]; then
	filename=aqua_${OS}_${ARCH}.zip
fi
URL=https://github.com/aquaproj/aqua/releases/download/$bootstrap_version/$filename

tempdir=$(mktemp -d)
echo "[INFO] Installing aqua $bootstrap_version for bootstrapping..." >&2
echo "[INFO] Downloading $URL ..." >&2
if command -v curl > /dev/null 2>&1; then
	curl --fail -L "$URL" -o "$tempdir/$filename"
elif command -v wget > /dev/null 2>&1; then
	wget -P "$tempdir" "$URL"
else
	echo "[ERROR] Neither curl nor wget is found. Please install either curl or wget to download aqua" >&2
	exit 1
fi

cd "$tempdir"

echo "[INFO] Verifying checksum of aqua $bootstrap_version ..." >&2
if command -v sha256sum > /dev/null 2>&1; then
	echo "$checksums" | grep "$filename" | sha256sum -c
elif command -v shasum > /dev/null 2>&1; then
	echo "$checksums" | grep "$filename" | shasum -a 256 -c
else
	echo "[WARN] Skipped checksum verification of aqua $bootstrap_version because both sha256sum and shasum commands aren't found" >&2
fi

if [ "$OS" = windows ]; then
	unzip "$filename" > /dev/null
else
	tar xvzf "$filename" > /dev/null
fi
chmod a+x aqua
if [ -n "${AQUA_VERSION:-}" ]; then
	echo "[INFO] $tempdir/aqua update-aqua $AQUA_VERSION" >&2
	./aqua update-aqua "$AQUA_VERSION"
else
	echo "[INFO] $tempdir/aqua update-aqua" >&2
	./aqua update-aqua
fi

echo ""
echo "==============================================================="
echo "[INFO] aqua is installed into $install_path" >&2
echo '[INFO] Please add the path to the environment variable "PATH"' >&2
# shellcheck disable=SC2016
install_dir='${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin'
if [ "$OS" = windows ]; then
	# shellcheck disable=SC2016
	install_dir='${AQUA_ROOT_DIR:-$HOME/AppData/Local/aquaproj-aqua}/bin'
fi
echo "[INFO] export PATH=$install_dir:\$PATH" >&2
echo "==============================================================="
echo ""

"$install_path" -v

rm -R "$tempdir"
