#!/usr/bin/env bash
# aqua-installer - shell script to install aqua
# https://github.com/aquaproj/aqua-installer

set -eu

usage_exit() {
  echo "Usage: $0 [-v version]" 1>&2
  exit 1
}

uname_os() {
  local os
  os=$(uname -s | tr '[:upper:]' '[:lower:]')
  case "$os" in
    cygwin_nt*) os="windows" ;;
    mingw*) os="windows" ;;
    msys_nt*) os="windows" ;;
  esac
  echo "$os"
}

uname_arch() {
  local arch
  arch=$(uname -m)
  case $arch in
    x86_64) arch="amd64" ;;
    aarch64) arch="arm64" ;;
  esac
  echo ${arch}
}

OS="$(uname_os)"
ARCH="$(uname_arch)"

install_path=${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin/aqua
if [ "$OS" = windows ]; then
  install_path=${AQUA_ROOT_DIR:-$HOME/AppData/Local/aquaproj-aqua}/bin/aqua.exe
fi

while getopts v: OPT
do
  case $OPT in
    v) version=$OPTARG
      ;;
    \?) usage_exit
      ;;
  esac
done

shift $((OPTIND - 1))

bootstrap_version=v2.16.4
checksums="34ad1e7f88e6fcc13f3bed2e7470ab570c4440aaa441e1b545cc514c571e9a2f  aqua_darwin_arm64.tar.gz
468c6c51f37196e6c21a096498eb4d3f7ba5cea3593b44af89087f571c207bc9  aqua_windows_amd64.tar.gz
6c2b6165000f3f2c5f04bbb52c8fe97b686cfbaa80493d866ad6770400b1773e  aqua_linux_arm64.tar.gz
7457ea4870f953de17c68fe8f86b3243c14890aa94a05e713d3c22ef401968b2  aqua_linux_amd64.tar.gz
c49f010e7e731ed62e7289169162001413f319cb593250a525aae26ee4551c3f  aqua_darwin_amd64.tar.gz
dcbc4c160827187504994a8f2ec4b5b7944a05da48b011de7a6cade9becd14e5  aqua_windows_arm64.tar.gz"

filename=aqua_${OS}_${ARCH}.tar.gz
URL=https://github.com/aquaproj/aqua/releases/download/$bootstrap_version/$filename

tempdir=$(mktemp -d)
echo "[INFO] Installing aqua $bootstrap_version for bootstrapping..." >&2
echo "[INFO] Downloading $URL ..." >&2
curl --fail -L "$URL" -o "$tempdir/$filename"

cd "$tempdir"

echo "[INFO] Verifying checksum of aqua $bootstrap_version ..." >&2
if command -v sha256sum > /dev/null 2>&1; then
  echo "$checksums" | grep "$filename" | sha256sum -c
elif command -v shasum > /dev/null 2>&1; then
  echo "$checksums" | grep "$filename" | shasum -a 256 -c
else
	echo "[WARN] Skipped checksum verification of aqua $bootstrap_version because both sha256sum and shasum commands aren't found" >&2
fi

tar xvzf "$filename" > /dev/null
chmod a+x aqua
if [ -n "${version:-}" ]; then
	echo "[INFO] $tempdir/aqua update-aqua $version" >&2
	./aqua update-aqua "$version"
else
	echo "[INFO] $tempdir/aqua update-aqua" >&2
	./aqua update-aqua
fi

echo ""
echo "==============================================================="
echo "[INFO] aqua is installed into $install_path" >&2
echo '[INFO] Please add the path to the environment variable "PATH"' >&2
echo "[INFO] export PATH=$(dirname "$install_path"):\$PATH" >&2
echo "==============================================================="
echo ""

"$install_path" -v

rm -R "$tempdir"
