---
name: Release
on:
  push:
    tags: ["*"]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - name: Install Cosign
        uses: aquaproj/aqua-installer@c553e04154f1f3b7e5eb35da058db3bb782bee8a # tag=v1.1.2
        with:
          aqua_version: v1.25.0
      - name: Sign aqua-installer with Cosign
        run: |
          echo "$COSIGN_KEY" > cosign.key
          cosign sign-blob \
            --key cosign.key \
            --output-signature aqua-installer.sig \
            aqua-installer
          rm cosign.key
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_KEY: ${{ secrets.KEY }}
      - name: Create a prerelease
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          draft: true
          files: |
            LICENSE
            aqua-installer
            aqua-installer.sig
