---
name: test
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: bash < aqua-installer
    - run: echo "${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin" >> "$GITHUB_PATH"
    - run: command -v aqua
    - run: aqua -v
  set-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: bash -s -- -v v0.1.0-9 < aqua-installer
    - run: echo "${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin" >> "$GITHUB_PATH"
    - run: command -v aqua
    - run: aqua -v
  set-absolute-path:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: bash -s -- -i /tmp/bin/aqua < aqua-installer
    - run: /tmp/bin/aqua -v
  set-relative-path:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: bash -s -- -i bin/aqua < aqua-installer
    - run: bin/aqua -v
