---
name: test (workflow_call)
on: workflow_call
permissions: {}
jobs:
  path-filter:
    # Get changed files to filter jobs
    timeout-minutes: 10
    outputs:
      update-aqua-checksums: ${{steps.changes.outputs.update-aqua-checksums}}
      renovate-config-validator: ${{steps.changes.outputs.renovate-config-validator}}
      ghalint: ${{steps.changes.outputs.ghalint}}
    runs-on: ubuntu-24.04
    permissions: {}
    steps:
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: changes
        with:
          filters: |
            renovate-config-validator:
              - renovate.json5
            ghalint:
              - .github/workflows/*.yaml
              - aqua/ghalint.yaml

  renovate-config-validator:
    # Validate Renovate Configuration by renovate-config-validator.
    uses: suzuki-shunsuke/github-action-renovate-config-validator/.github/workflows/renovate-config-validator.yaml@1e1604219a6b38ae9a10aff42a28a3656322c31a # v2.4.1
    needs: path-filter
    if: needs.path-filter.outputs.renovate-config-validator == 'true'
    permissions:
      contents: read

  ghalint:
    # Validate GitHub Actions Workflows by ghalint.
    timeout-minutes: 20
    needs: path-filter
    if: needs.path-filter.outputs.ghalint == 'true'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./
        with:
          aqua_version: v2.63.0
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: ghalint run
        env:
          GHALINT_LOG_COLOR: always
          AQUA_GITHUB_TOKEN: ${{github.token}}

  test-script:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: ./aqua-installer
      - run: echo "${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin" >> "$GITHUB_PATH"
      - run: command -v aqua
      - run: aqua -v

  test-script-set-version:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: bash -s -- -v v2.50.0 < aqua-installer
      - run: echo "${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin" >> "$GITHUB_PATH"
      - run: command -v aqua
      - run: aqua -v

  test-action-linux:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./
        with:
          aqua_version: v2.63.0
          working_directory: tests
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: command -v aqua
      - run: aqua -v
      - run: ghalint -v
        env:
          GITHUB_TOKEN: ${{ github.token }}

  test-action-container:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    container:
      image: mirror.gcr.io/golang:1.25.4@sha256:5d73b7b83dd6e0258ff62832c93b6ea208fbb7727985d265fb49f75f81fc3d1f
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./
        with:
          aqua_version: v2.63.0
          working_directory: tests
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: command -v aqua
      - run: aqua -v
      - run: ghalint -v
        env:
          GITHUB_TOKEN: ${{ github.token }}

  test-action-macos:
    timeout-minutes: 20
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./
        with:
          aqua_version: v2.63.0
          working_directory: tests
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: command -v aqua
      - run: aqua -v
      - run: ghalint -v
        env:
          GITHUB_TOKEN: ${{ github.token }}

  test-action-windows-normal:
    timeout-minutes: 20
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./
        with:
          aqua_version: v2.63.0
      - run: command -v aqua
        shell: bash
      - run: aqua -v
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: ghalint -v
        shell: bash
        working-directory: tests
        env:
          GITHUB_TOKEN: ${{ github.token }}

  test-action-windows-working_dir:
    timeout-minutes: 20
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./
        with:
          aqua_version: v2.63.0
          working_directory: tests

      - run: command -v aqua
        shell: bash
      - run: aqua -v
        shell: bash
      - run: ghalint -v
        env:
          GITHUB_TOKEN: ${{ github.token }}
